spring:
  application:
    name: my-redis
    #整合哨兵机制集群
  redis:
    password: redis
    sentinel:
      master: mymaster
      nodes: 192.168.7.231:26379,192.168.7.232:26378,192.168.7.233:26377
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.7.8:1521/orcl
    username: gzpost
    password: gzpost
    hikari:
      connection-timeout: 60000
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 60000
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://eureka1-server:8761/eureka/,http://eureka2-server:8762/eureka/
mybatis:
  mapper-locations: classpath*:/com/myself/devp/myrediscenter/model/mapper/*.xml
  type-aliases-package: com.myself.devp.myrediscenter.model

