spring:
  application:
    name: my-redis
  redis:
    host: localhost
    password:
    port: 6379
  profiles:
    include:
      - rediscof
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.7.8:1521/orcl
    username: gzpost
    password: gzpost
    hikari:
      connection-timeout: 60000
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 60000
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://eureka1-server:8761/eureka/,http://eureka2-server:8762/eureka/
mybatis:
  config-location: classpath:com/myself/devp/myrediscenter/mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml

