spring:
  application:
    name: my-usercenter
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eureka1-server:8761/eureka/,http://eureka2-server:8762/eureka/
feign:
  hystrix:
    enabled: true #开启熔断支持
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
logging:
  level:
    com.myself.devp.myusercenter.core.filter.FeignAcceptGzipEncodingIntercepter: DEBUG
  #将Feign接口的日志级别为DEBUG，因为Feign的Logger.Level
  #只对DEBUG做出响应
