spring:
  application:
    name: my-eureka1
server:
  port: 8761
eureka:
  #指定主机名称
  instance:
    hostname: eureka1-server
  #server一定程度上也是client 互为client
  client:
    #由于自己就是注册中心，不需要注册自己
    register-with-eureka: false
    #由于自己就是服务器，   不需要从服务器获取自己
    #fetch-registry: false
    #服务地址
    service-url:
      defaultZone: http://eureka2-server:8762/eureka/

